# This is a basic workflow to help you get started with Actions

name: pusher
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slackNotification:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_CHANNEL: tools
          SLACK_MESSAGE: ‘New updates on https://github.com/gexpose/synackAPI
          SLACK_TITLE: ‘API class update’
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }
